import { Product } from '@/types';

// Static product catalogue for Master Miller
// Images can be uploaded via admin dashboard once available from Google Drive
const now = new Date();

export const staticProducts: Product[] = [
  // ─── FLOUR ───────────────────────────────────────────────────
  {
    id: 'static-flour-001',
    name: 'Whole Wheat Chakki Atta',
    nameHindi: 'चक्की आटा',
    category: 'flour',
    description: 'Stone-ground whole wheat flour, freshly milled preserving natural bran and germ. Perfect for soft, nutritious rotis.',
    price: 90,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-002',
    name: 'Multigrain Atta',
    nameHindi: 'मल्टीग्रेन आटा',
    category: 'flour',
    description: 'A nutritious blend of wheat, jowar, bajra, ragi, and soybean. High in fibre and protein, ideal for healthy rotis.',
    price: 120,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-003',
    name: 'Besan (Gram Flour)',
    nameHindi: 'बेसन',
    category: 'flour',
    description: 'Freshly ground chickpea flour with a rich, nutty aroma. Essential for pakoras, cheela, and traditional sweets.',
    price: 160,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-004',
    name: 'Jowar Flour',
    nameHindi: 'ज्वार आटा',
    category: 'flour',
    description: 'Gluten-free sorghum flour, stone-milled for maximum nutrition. Great for diabetics and health-conscious eaters.',
    price: 100,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-005',
    name: 'Bajra Flour',
    nameHindi: 'बाजरा आटा',
    category: 'flour',
    description: 'Pearl millet flour rich in iron, calcium, and fibre. Traditional winter staple for warm, hearty rotis.',
    price: 80,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-006',
    name: 'Ragi Flour',
    nameHindi: 'रागी आटा',
    category: 'flour',
    description: 'Finger millet flour, a superfood packed with calcium and amino acids. Excellent for weight management.',
    price: 130,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-007',
    name: 'Maize Flour (Makki Atta)',
    nameHindi: 'मक्की आटा',
    category: 'flour',
    description: 'Coarsely ground corn flour for authentic Makki di Roti. Naturally gluten-free and full of antioxidants.',
    price: 82,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-flour-008',
    name: 'Maida (Refined Flour)',
    nameHindi: 'मैदा',
    category: 'flour',
    description: 'Finely milled refined wheat flour. Ideal for baking, parathas, and festive sweets.',
    price: 55,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },

  // ─── SPICES ─────────────────────────────────────────────────
  {
    id: 'static-spice-001',
    name: 'Red Chilli Powder',
    nameHindi: 'लाल मिर्च पाउडर',
    category: 'spices',
    description: 'Freshly ground red chilli powder with vibrant colour and heat. Made from handpicked dried chillies.',
    price: 80,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-spice-002',
    name: 'Coriander Powder',
    nameHindi: 'धनिया पाउडर',
    category: 'spices',
    description: 'Aromatic ground coriander with a citrusy, earthy flavour. Freshly milled to retain maximum aroma.',
    price: 35,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-spice-003',
    name: 'Turmeric Powder',
    nameHindi: 'हल्दी पाउडर',
    category: 'spices',
    description: 'High-curcumin turmeric freshly ground for intense colour and health benefits. A kitchen essential.',
    price: 40,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-spice-004',
    name: 'Garam Masala',
    nameHindi: 'गरम मसाला',
    category: 'spices',
    description: 'A premium blend of 12 whole spices ground fresh. Adds depth and warmth to every Indian dish.',
    price: 175,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-spice-005',
    name: 'Cumin Seeds (Sabut Jeera)',
    nameHindi: 'जीरा',
    category: 'spices',
    description: 'Premium whole cumin seeds with a strong, earthy aroma. Sourced from the best growing regions.',
    price: 80,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-spice-006',
    name: 'Black Mustard Seeds',
    nameHindi: 'राई',
    category: 'spices',
    description: 'Whole black mustard seeds, essential for tempering. Strong, pungent flavour that elevates any dish.',
    price: 20,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },

  // ─── OILS ────────────────────────────────────────────────────
  {
    id: 'static-oil-001',
    name: 'Cold Pressed Mustard Oil',
    nameHindi: 'कच्ची घानी सरसों तेल',
    category: 'oils',
    description: 'Traditional cold-pressed (kachi ghani) mustard oil with a pungent aroma. No heat treatment — full nutrition preserved.',
    price: 450,
    unit: '1 L',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-oil-002',
    name: 'Cold Pressed Sesame Oil',
    nameHindi: 'तिल तेल',
    category: 'oils',
    description: 'Wood-pressed white sesame oil, rich in antioxidants and healthy fats. Nutty flavour, ideal for cooking and skin.',
    price: 650,
    unit: '1 L',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-oil-003',
    name: 'Cold Pressed Groundnut Oil',
    nameHindi: 'मूंगफली तेल',
    category: 'oils',
    description: 'Naturally extracted peanut oil with a mild nutty flavour. High smoke point, perfect for frying and sautéing.',
    price: 555,
    unit: '1 L',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-oil-004',
    name: 'Virgin Coconut Oil',
    nameHindi: 'नारियल तेल',
    category: 'oils',
    description: 'Cold-pressed virgin coconut oil, unrefined and chemical-free. Excellent for cooking, hair, and skin care.',
    price: 490,
    unit: '500 ml',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-oil-005',
    name: 'Flaxseed Oil',
    nameHindi: 'अलसी तेल',
    category: 'oils',
    description: 'Rich in Omega-3 fatty acids. Cold-pressed from premium flaxseeds. Best consumed raw as a nutritional supplement.',
    price: 280,
    unit: '500 ml',
    imageUrl: '',
    inStock: false,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },

  // ─── PULSES ──────────────────────────────────────────────────
  {
    id: 'static-pulse-001',
    name: 'Moong Dal (Split)',
    nameHindi: 'मूंग दाल',
    category: 'pulses',
    description: 'Tender split green gram, easy to digest and quick to cook. A protein-rich staple in every Indian household.',
    price: 88,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-pulse-002',
    name: 'Masoor Dal (Red Lentils)',
    nameHindi: 'मसूर दाल',
    category: 'pulses',
    description: 'Red lentils that cook quickly and are rich in protein and folate. Mild flavour, ideal for everyday dal.',
    price: 90,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-pulse-003',
    name: 'Chana Dal',
    nameHindi: 'चना दाल',
    category: 'pulses',
    description: 'Split Bengal gram with a nutty flavour and low glycaemic index. Great for dal, curries, and besan preparation.',
    price: 85,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-pulse-004',
    name: 'Arhar Dal (Toor Dal)',
    nameHindi: 'अरहर दाल',
    category: 'pulses',
    description: 'Split pigeon peas — the classic dal for sambar and everyday meals. Rich in protein, low in fat.',
    price: 98,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-pulse-005',
    name: 'Urad Dal (Black Gram)',
    nameHindi: 'उड़द दाल',
    category: 'pulses',
    description: 'Split black gram, essential for dal makhani and idli-dosa batter. High in protein and calcium.',
    price: 98,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-pulse-006',
    name: 'Kabuli Chana (Chickpeas)',
    nameHindi: 'काबुली चना',
    category: 'pulses',
    description: 'Large white chickpeas, rich in fibre and plant protein. Perfect for chole, salads, and hummus.',
    price: 88,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },

  // ─── GRAINS ──────────────────────────────────────────────────
  {
    id: 'static-grain-001',
    name: 'Brown Rice',
    nameHindi: 'भूरा चावल',
    category: 'grains',
    description: 'Unpolished brown rice retaining its bran and germ. Nutty flavour, higher fibre and nutrition than white rice.',
    price: 160,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-grain-002',
    name: 'Premium Basmati Rice',
    nameHindi: 'बासमती चावल',
    category: 'grains',
    description: 'Long-grain aged basmati with a delicate floral aroma. The finest quality for biryanis and pulao.',
    price: 180,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-grain-003',
    name: 'Foxtail Millet (Kangni)',
    nameHindi: 'कांगनी',
    category: 'grains',
    description: 'An ancient millet grain, rich in iron and calcium. Gluten-free superfood for khichdi, porridge, and more.',
    price: 85,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-grain-004',
    name: 'Barnyard Millet (Sanwa)',
    nameHindi: 'सांवा',
    category: 'grains',
    description: 'A highly nutritious millet with low glycaemic index. Ideal for fasting days (vrat) and healthy cooking.',
    price: 220,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-grain-005',
    name: 'Whole Jowar (Sorghum)',
    nameHindi: 'साबुत ज्वार',
    category: 'grains',
    description: 'Whole sorghum grains, gluten-free and nutrient-dense. Can be cooked as rice, popped, or ground fresh.',
    price: 100,
    unit: '1 kg',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },

  // ─── OTHERS ──────────────────────────────────────────────────
  {
    id: 'static-other-001',
    name: 'Rock Salt (Sendha Namak)',
    nameHindi: 'सेंधा नमक',
    category: 'others',
    description: 'Pure Himalayan pink rock salt, unprocessed and mineral-rich. Ideal for everyday use and fasting rituals.',
    price: 63,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-other-002',
    name: 'Jaggery Powder (Gur)',
    nameHindi: 'गुड़ पाउडर',
    category: 'others',
    description: 'Unrefined natural jaggery powder — a healthy alternative to refined sugar. Rich in iron and minerals.',
    price: 75,
    unit: '500 g',
    imageUrl: '',
    inStock: true,
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-other-003',
    name: 'Flaxseeds (Alsi)',
    nameHindi: 'अलसी',
    category: 'others',
    description: 'Whole golden flaxseeds rich in Omega-3 fatty acids, fibre, and lignans. Add to smoothies, rotis, or salads.',
    price: 55,
    unit: '200 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-other-004',
    name: 'Sesame Seeds (Til)',
    nameHindi: 'तिल',
    category: 'others',
    description: 'Premium white sesame seeds, hulled and cleaned. Rich in calcium and healthy fats. Used in chikkis and tahini.',
    price: 75,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'static-other-005',
    name: 'Dry Mango Powder (Amchur)',
    nameHindi: 'अमचूर',
    category: 'others',
    description: 'Tangy dried green mango powder for chaats, curries, and marinades. Freshly ground for intense sour flavour.',
    price: 68,
    unit: '100 g',
    imageUrl: '',
    inStock: true,
    featured: false,
    createdAt: now,
    updatedAt: now,
  },
];
